/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteRgerrerArgs } from "./DeleteRgerrerArgs";
import { RgerrerFindManyArgs } from "./RgerrerFindManyArgs";
import { RgerrerFindUniqueArgs } from "./RgerrerFindUniqueArgs";
import { Rgerrer } from "./Rgerrer";
import { RgerrerService } from "../rgerrer.service";

@graphql.Resolver(() => Rgerrer)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class RgerrerResolverBase {
  constructor(
    protected readonly service: RgerrerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Rgerrer",
    action: "read",
    possession: "any",
  })
  async _rgerrersMeta(
    @graphql.Args() args: RgerrerFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Rgerrer])
  @nestAccessControl.UseRoles({
    resource: "Rgerrer",
    action: "read",
    possession: "any",
  })
  async rgerrers(
    @graphql.Args() args: RgerrerFindManyArgs
  ): Promise<Rgerrer[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Rgerrer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Rgerrer",
    action: "read",
    possession: "own",
  })
  async rgerrer(
    @graphql.Args() args: RgerrerFindUniqueArgs
  ): Promise<Rgerrer | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Rgerrer)
  @nestAccessControl.UseRoles({
    resource: "Rgerrer",
    action: "delete",
    possession: "any",
  })
  async deleteRgerrer(
    @graphql.Args() args: DeleteRgerrerArgs
  ): Promise<Rgerrer | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
