/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteRvllVsdfArgs } from "./DeleteRvllVsdfArgs";
import { RvllVsdfFindManyArgs } from "./RvllVsdfFindManyArgs";
import { RvllVsdfFindUniqueArgs } from "./RvllVsdfFindUniqueArgs";
import { RvllVsdf } from "./RvllVsdf";
import { RvllVsdfService } from "../rvllVsdf.service";

@graphql.Resolver(() => RvllVsdf)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class RvllVsdfResolverBase {
  constructor(
    protected readonly service: RvllVsdfService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "RvllVsdf",
    action: "read",
    possession: "any",
  })
  async _rvllVsdfsMeta(
    @graphql.Args() args: RvllVsdfFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [RvllVsdf])
  @nestAccessControl.UseRoles({
    resource: "RvllVsdf",
    action: "read",
    possession: "any",
  })
  async rvllVsdfs(
    @graphql.Args() args: RvllVsdfFindManyArgs
  ): Promise<RvllVsdf[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => RvllVsdf, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "RvllVsdf",
    action: "read",
    possession: "own",
  })
  async rvllVsdf(
    @graphql.Args() args: RvllVsdfFindUniqueArgs
  ): Promise<RvllVsdf | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => RvllVsdf)
  @nestAccessControl.UseRoles({
    resource: "RvllVsdf",
    action: "delete",
    possession: "any",
  })
  async deleteRvllVsdf(
    @graphql.Args() args: DeleteRvllVsdfArgs
  ): Promise<RvllVsdf | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
